//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3074
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.echo.EchoOne.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.echo.EchoOne.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Kombine_toolbar_007 {
            get {
                object obj = ResourceManager.GetObject("Kombine_toolbar_007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kombine_toolbar_008 {
            get {
                object obj = ResourceManager.GetObject("Kombine_toolbar_008", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kombine_toolbar_009 {
            get {
                object obj = ResourceManager.GetObject("Kombine_toolbar_009", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kombine_toolbar_010 {
            get {
                object obj = ResourceManager.GetObject("Kombine_toolbar_010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kombine_toolbar_013 {
            get {
                object obj = ResourceManager.GetObject("Kombine_toolbar_013", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kombine_toolbar_015 {
            get {
                object obj = ResourceManager.GetObject("Kombine_toolbar_015", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kombine_toolbar_017 {
            get {
                object obj = ResourceManager.GetObject("Kombine_toolbar_017", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kombine_toolbar_018 {
            get {
                object obj = ResourceManager.GetObject("Kombine_toolbar_018", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kombine_toolbar_019 {
            get {
                object obj = ResourceManager.GetObject("Kombine_toolbar_019", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kombine_toolbar_020 {
            get {
                object obj = ResourceManager.GetObject("Kombine_toolbar_020", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kombine_toolbar_023 {
            get {
                object obj = ResourceManager.GetObject("Kombine_toolbar_023", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kombine_toolbar_025 {
            get {
                object obj = ResourceManager.GetObject("Kombine_toolbar_025", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kombine_toolbar_029 {
            get {
                object obj = ResourceManager.GetObject("Kombine_toolbar_029", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kombine_toolbar_039 {
            get {
                object obj = ResourceManager.GetObject("Kombine_toolbar_039", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kombine_toolbar_040 {
            get {
                object obj = ResourceManager.GetObject("Kombine_toolbar_040", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kombine_toolbar_041 {
            get {
                object obj = ResourceManager.GetObject("Kombine_toolbar_041", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kombine_toolbar_042 {
            get {
                object obj = ResourceManager.GetObject("Kombine_toolbar_042", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kombine_toolbar_043 {
            get {
                object obj = ResourceManager.GetObject("Kombine_toolbar_043", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kombine_toolbar_044 {
            get {
                object obj = ResourceManager.GetObject("Kombine_toolbar_044", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kombine_toolbar_045 {
            get {
                object obj = ResourceManager.GetObject("Kombine_toolbar_045", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
