//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4200
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.4200 版自动生成。
// 
#pragma warning disable 1591

namespace com.echo.PartyMemberOM.WebServices {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EchoOneWSSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class EchoOneWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetRolesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsersByRoleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDeptsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserByDeptOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFunctionByUserIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EchoOneWS() {
            this.Url = global::com.echo.PartyMemberOM.Properties.Settings.Default.EchoOneWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetRolesCompletedEventHandler GetRolesCompleted;
        
        /// <remarks/>
        public event GetUsersByRoleCompletedEventHandler GetUsersByRoleCompleted;
        
        /// <remarks/>
        public event GetDeptsCompletedEventHandler GetDeptsCompleted;
        
        /// <remarks/>
        public event GetUserByDeptCompletedEventHandler GetUserByDeptCompleted;
        
        /// <remarks/>
        public event ValidUserCompletedEventHandler ValidUserCompleted;
        
        /// <remarks/>
        public event GetUserByNameCompletedEventHandler GetUserByNameCompleted;
        
        /// <remarks/>
        public event GetFunctionByUserIdCompletedEventHandler GetFunctionByUserIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRoles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] GetRoles() {
            object[] results = this.Invoke("GetRoles", new object[0]);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRolesAsync() {
            this.GetRolesAsync(null);
        }
        
        /// <remarks/>
        public void GetRolesAsync(object userState) {
            if ((this.GetRolesOperationCompleted == null)) {
                this.GetRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRolesOperationCompleted);
            }
            this.InvokeAsync("GetRoles", new object[0], this.GetRolesOperationCompleted, userState);
        }
        
        private void OnGetRolesOperationCompleted(object arg) {
            if ((this.GetRolesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRolesCompleted(this, new GetRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUsersByRole", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] GetUsersByRole(string roleName) {
            object[] results = this.Invoke("GetUsersByRole", new object[] {
                        roleName});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersByRoleAsync(string roleName) {
            this.GetUsersByRoleAsync(roleName, null);
        }
        
        /// <remarks/>
        public void GetUsersByRoleAsync(string roleName, object userState) {
            if ((this.GetUsersByRoleOperationCompleted == null)) {
                this.GetUsersByRoleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersByRoleOperationCompleted);
            }
            this.InvokeAsync("GetUsersByRole", new object[] {
                        roleName}, this.GetUsersByRoleOperationCompleted, userState);
        }
        
        private void OnGetUsersByRoleOperationCompleted(object arg) {
            if ((this.GetUsersByRoleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersByRoleCompleted(this, new GetUsersByRoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDepts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] GetDepts() {
            object[] results = this.Invoke("GetDepts", new object[0]);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDeptsAsync() {
            this.GetDeptsAsync(null);
        }
        
        /// <remarks/>
        public void GetDeptsAsync(object userState) {
            if ((this.GetDeptsOperationCompleted == null)) {
                this.GetDeptsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeptsOperationCompleted);
            }
            this.InvokeAsync("GetDepts", new object[0], this.GetDeptsOperationCompleted, userState);
        }
        
        private void OnGetDeptsOperationCompleted(object arg) {
            if ((this.GetDeptsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDeptsCompleted(this, new GetDeptsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserByDept", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] GetUserByDept(string deptName) {
            object[] results = this.Invoke("GetUserByDept", new object[] {
                        deptName});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUserByDeptAsync(string deptName) {
            this.GetUserByDeptAsync(deptName, null);
        }
        
        /// <remarks/>
        public void GetUserByDeptAsync(string deptName, object userState) {
            if ((this.GetUserByDeptOperationCompleted == null)) {
                this.GetUserByDeptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserByDeptOperationCompleted);
            }
            this.InvokeAsync("GetUserByDept", new object[] {
                        deptName}, this.GetUserByDeptOperationCompleted, userState);
        }
        
        private void OnGetUserByDeptOperationCompleted(object arg) {
            if ((this.GetUserByDeptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserByDeptCompleted(this, new GetUserByDeptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidUser(string userName, string password) {
            object[] results = this.Invoke("ValidUser", new object[] {
                        userName,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidUserAsync(string userName, string password) {
            this.ValidUserAsync(userName, password, null);
        }
        
        /// <remarks/>
        public void ValidUserAsync(string userName, string password, object userState) {
            if ((this.ValidUserOperationCompleted == null)) {
                this.ValidUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidUserOperationCompleted);
            }
            this.InvokeAsync("ValidUser", new object[] {
                        userName,
                        password}, this.ValidUserOperationCompleted, userState);
        }
        
        private void OnValidUserOperationCompleted(object arg) {
            if ((this.ValidUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidUserCompleted(this, new ValidUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User GetUserByName(string userName) {
            object[] results = this.Invoke("GetUserByName", new object[] {
                        userName});
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserByNameAsync(string userName) {
            this.GetUserByNameAsync(userName, null);
        }
        
        /// <remarks/>
        public void GetUserByNameAsync(string userName, object userState) {
            if ((this.GetUserByNameOperationCompleted == null)) {
                this.GetUserByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserByNameOperationCompleted);
            }
            this.InvokeAsync("GetUserByName", new object[] {
                        userName}, this.GetUserByNameOperationCompleted, userState);
        }
        
        private void OnGetUserByNameOperationCompleted(object arg) {
            if ((this.GetUserByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserByNameCompleted(this, new GetUserByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFunctionByUserId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Function[] GetFunctionByUserId(System.Guid userId) {
            object[] results = this.Invoke("GetFunctionByUserId", new object[] {
                        userId});
            return ((Function[])(results[0]));
        }
        
        /// <remarks/>
        public void GetFunctionByUserIdAsync(System.Guid userId) {
            this.GetFunctionByUserIdAsync(userId, null);
        }
        
        /// <remarks/>
        public void GetFunctionByUserIdAsync(System.Guid userId, object userState) {
            if ((this.GetFunctionByUserIdOperationCompleted == null)) {
                this.GetFunctionByUserIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFunctionByUserIdOperationCompleted);
            }
            this.InvokeAsync("GetFunctionByUserId", new object[] {
                        userId}, this.GetFunctionByUserIdOperationCompleted, userState);
        }
        
        private void OnGetFunctionByUserIdOperationCompleted(object arg) {
            if ((this.GetFunctionByUserIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFunctionByUserIdCompleted(this, new GetFunctionByUserIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FuncType {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FuncInRole {
        
        private System.Guid funcIdField;
        
        private System.Guid roleIdField;
        
        /// <remarks/>
        public System.Guid FuncId {
            get {
                return this.funcIdField;
            }
            set {
                this.funcIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Function {
        
        private System.Guid idField;
        
        private string nameField;
        
        private int funcTypeField;
        
        private string pathField;
        
        private int imgIndexField;
        
        private FuncInRole[] funcInRoleField;
        
        private FuncType funcType1Field;
        
        /// <remarks/>
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int FuncType {
            get {
                return this.funcTypeField;
            }
            set {
                this.funcTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public int ImgIndex {
            get {
                return this.imgIndexField;
            }
            set {
                this.imgIndexField = value;
            }
        }
        
        /// <remarks/>
        public FuncInRole[] FuncInRole {
            get {
                return this.funcInRoleField;
            }
            set {
                this.funcInRoleField = value;
            }
        }
        
        /// <remarks/>
        public FuncType FuncType1 {
            get {
                return this.funcType1Field;
            }
            set {
                this.funcType1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Dept {
        
        private int idField;
        
        private string deptNameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string DeptName {
            get {
                return this.deptNameField;
            }
            set {
                this.deptNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserInDept {
        
        private System.Guid userIdField;
        
        private int deptIdField;
        
        private Dept deptField;
        
        /// <remarks/>
        public System.Guid UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public int DeptId {
            get {
                return this.deptIdField;
            }
            set {
                this.deptIdField = value;
            }
        }
        
        /// <remarks/>
        public Dept Dept {
            get {
                return this.deptField;
            }
            set {
                this.deptField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Membership {
        
        private System.Guid applicationIdField;
        
        private System.Guid userIdField;
        
        private string passwordField;
        
        private int passwordFormatField;
        
        private string passwordSaltField;
        
        private string mobilePINField;
        
        private string emailField;
        
        private string loweredEmailField;
        
        private string passwordQuestionField;
        
        private string passwordAnswerField;
        
        private bool isApprovedField;
        
        private bool isLockedOutField;
        
        private System.DateTime createDateField;
        
        private System.DateTime lastLoginDateField;
        
        private System.DateTime lastPasswordChangedDateField;
        
        private System.DateTime lastLockoutDateField;
        
        private int failedPasswordAttemptCountField;
        
        private System.DateTime failedPasswordAttemptWindowStartField;
        
        private int failedPasswordAnswerAttemptCountField;
        
        private System.DateTime failedPasswordAnswerAttemptWindowStartField;
        
        private string commentField;
        
        /// <remarks/>
        public System.Guid ApplicationId {
            get {
                return this.applicationIdField;
            }
            set {
                this.applicationIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int PasswordFormat {
            get {
                return this.passwordFormatField;
            }
            set {
                this.passwordFormatField = value;
            }
        }
        
        /// <remarks/>
        public string PasswordSalt {
            get {
                return this.passwordSaltField;
            }
            set {
                this.passwordSaltField = value;
            }
        }
        
        /// <remarks/>
        public string MobilePIN {
            get {
                return this.mobilePINField;
            }
            set {
                this.mobilePINField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string LoweredEmail {
            get {
                return this.loweredEmailField;
            }
            set {
                this.loweredEmailField = value;
            }
        }
        
        /// <remarks/>
        public string PasswordQuestion {
            get {
                return this.passwordQuestionField;
            }
            set {
                this.passwordQuestionField = value;
            }
        }
        
        /// <remarks/>
        public string PasswordAnswer {
            get {
                return this.passwordAnswerField;
            }
            set {
                this.passwordAnswerField = value;
            }
        }
        
        /// <remarks/>
        public bool IsApproved {
            get {
                return this.isApprovedField;
            }
            set {
                this.isApprovedField = value;
            }
        }
        
        /// <remarks/>
        public bool IsLockedOut {
            get {
                return this.isLockedOutField;
            }
            set {
                this.isLockedOutField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastLoginDate {
            get {
                return this.lastLoginDateField;
            }
            set {
                this.lastLoginDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastPasswordChangedDate {
            get {
                return this.lastPasswordChangedDateField;
            }
            set {
                this.lastPasswordChangedDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastLockoutDate {
            get {
                return this.lastLockoutDateField;
            }
            set {
                this.lastLockoutDateField = value;
            }
        }
        
        /// <remarks/>
        public int FailedPasswordAttemptCount {
            get {
                return this.failedPasswordAttemptCountField;
            }
            set {
                this.failedPasswordAttemptCountField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FailedPasswordAttemptWindowStart {
            get {
                return this.failedPasswordAttemptWindowStartField;
            }
            set {
                this.failedPasswordAttemptWindowStartField = value;
            }
        }
        
        /// <remarks/>
        public int FailedPasswordAnswerAttemptCount {
            get {
                return this.failedPasswordAnswerAttemptCountField;
            }
            set {
                this.failedPasswordAnswerAttemptCountField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FailedPasswordAnswerAttemptWindowStart {
            get {
                return this.failedPasswordAnswerAttemptWindowStartField;
            }
            set {
                this.failedPasswordAnswerAttemptWindowStartField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UsersInRole {
        
        private System.Guid userIdField;
        
        private System.Guid roleIdField;
        
        /// <remarks/>
        public System.Guid UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class User {
        
        private System.Guid applicationIdField;
        
        private System.Guid userIdField;
        
        private string userNameField;
        
        private string loweredUserNameField;
        
        private string mobileAliasField;
        
        private bool isAnonymousField;
        
        private System.DateTime lastActivityDateField;
        
        private UsersInRole[] usersInRoleField;
        
        private Membership membershipField;
        
        private UserInDept userInDeptField;
        
        /// <remarks/>
        public System.Guid ApplicationId {
            get {
                return this.applicationIdField;
            }
            set {
                this.applicationIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string LoweredUserName {
            get {
                return this.loweredUserNameField;
            }
            set {
                this.loweredUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string MobileAlias {
            get {
                return this.mobileAliasField;
            }
            set {
                this.mobileAliasField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAnonymous {
            get {
                return this.isAnonymousField;
            }
            set {
                this.isAnonymousField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastActivityDate {
            get {
                return this.lastActivityDateField;
            }
            set {
                this.lastActivityDateField = value;
            }
        }
        
        /// <remarks/>
        public UsersInRole[] UsersInRole {
            get {
                return this.usersInRoleField;
            }
            set {
                this.usersInRoleField = value;
            }
        }
        
        /// <remarks/>
        public Membership Membership {
            get {
                return this.membershipField;
            }
            set {
                this.membershipField = value;
            }
        }
        
        /// <remarks/>
        public UserInDept UserInDept {
            get {
                return this.userInDeptField;
            }
            set {
                this.userInDeptField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetRolesCompletedEventHandler(object sender, GetRolesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetUsersByRoleCompletedEventHandler(object sender, GetUsersByRoleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersByRoleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersByRoleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetDeptsCompletedEventHandler(object sender, GetDeptsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDeptsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDeptsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetUserByDeptCompletedEventHandler(object sender, GetUserByDeptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserByDeptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserByDeptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void ValidUserCompletedEventHandler(object sender, ValidUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetUserByNameCompletedEventHandler(object sender, GetUserByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetFunctionByUserIdCompletedEventHandler(object sender, GetFunctionByUserIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFunctionByUserIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFunctionByUserIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Function[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Function[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591